import astroDtsBuilder from "@matthiesenxyz/astrodtsbuilder";
import { name } from "../package.json";

// Create the config DTS file
const config = astroDtsBuilder();

// Add a note to the top of the file
config.addSingleLineNote(
	`This file is generated by '${name}' and should not be modified manually.`,
);

// Add the module to the file
config.addModule("virtual:astro-turnstile/config", {
	defaultExport: {
		typeDef: `import("${name}/schema").AstroTurnstileOptions`,
		singleLineDescription: "The Turnstile configuration options",
	},
});

// Create the components DTS file
const components = astroDtsBuilder();

// Add a note to the top of the file
components.addSingleLineNote(
	`This file is generated by '${name}' and should not be modified manually.`,
);

// Add the module to the file
components.addModule("astro-turnstile:components", {
	namedExports: [
		{
			name: "TurnstileForm",
			typeDef: `typeof import('${name}/components').TurnstileForm`,
			multiLineDescription: [
				"# The Turnstile form component.",
				"@description An [Astro](https://astro.build) component that is used to render a form that will be protected by Cloudflare Turnstile.",
				"@param {string} action - The action attribute for the form.",
				"@param {string} method - The method attribute for the form.",
				'@param {"auto"|"light"|"dark"} theme - The theme for the form. `(default: "auto")`',
				'@param {"normal"|"compact"|"flexible"} size - The size for the form. `(default: "normal")`',
				"@param {string} margin - The margin for the form element. `(default: '0.5rem')`",
			],
		},
	],
});

// Export the DTS files
export default {
	config: config.makeAstroInjectedType("config.d.ts"),
	components: components.makeAstroInjectedType("components.d.ts"),
};
