import { name } from "../package.json";

const config = {
	filename: "config.d.ts",
	content: `// This file is generated by '${name}' and should not be modified manually.
declare module "virtual:astro-turnstile/config" {
	/** The Turnstile configuration options */
	const config: import("${name}/schema").AstroTurnstileConfig;
	export default config;
}`,
};

const components = {
	filename: "components.d.ts",
	content: `// This file is generated by '${name}' and should not be modified manually.
declare module "astro-turnstile:components/TurnstileWidget" {
	/**
	 * # Turnstile Verification Widget
	 * @description An [Astro](https://astro.build) component that is used to render a Turnstile verification widget. This widget is used to verify that a user is human.
	 * @param {"auto"|"light"|"dark"} theme - The theme for the widget. (default: "auto")
	 * @param {"normal"|"compact"|"flexible"} size - The size for the widget. (default: "normal")
	 * @param {string} margin - The margin for the widget element. (default: '0.5rem')
	 * @param {"render"|"execute"} execution - Execution mode. (default: "render")
	 * @param {"always"|"execute"|"interaction-only"} appearance - Appearance mode. (default: "always")
	 * @param {string} callback - Name of a global function called on successful verification
	 * @param {string} errorCallback - Name of a global function called on error
	 * @param {string} expiredCallback - Name of a global function called when token expires
	 * @param {string} timeoutCallback - Name of a global function called on timeout
	 * @param {string} beforeInteractiveCallback - Name of a global function called before interactive challenge
	 * @param {string} afterInteractiveCallback - Name of a global function called after interactive challenge
	 * @param {string} unsupportedCallback - Name of a global function called when browser is unsupported
	 * @example
	 * \`\`\`tsx
	 * ---
	 * import TurnstileWidget from '${name}:components/TurnstileWidget';
	 * ---
	 * <form action='/your/api/endpoint' method='POST'>
	 * <TurnstileWidget theme='light' size='compact' margin='1rem' />
	 * <button type='submit'>Submit</button>
	 * </form>
	 * \`\`\`
	 */
	const TurnstileWidget: typeof import("${name}/components/TurnstileWidget").default;
	export default TurnstileWidget;
}
declare module "astro-turnstile:components/TurnstileForm" {
	/**
	 * # Turnstile Verification Form
	 * @description An [Astro](https://astro.build) component that is used to render a Turnstile verification form. This form includes a Turnstile verification widget and a submit button.
	 * @slot default - Any unassigned content will be placed here.
	 * @slot header - \`<div slot='header'>...</div>\`
	 * @slot buttons - \`<div slot='buttons'>...</div>\`
	 * @slot footer - \`<div slot='footer'>...</div>\`
	 * @param {"auto"|"light"|"dark"} theme - The theme for the widget. (default: "auto")
	 * @param {"normal"|"compact"|"flexible"} size - The size for the widget. (default: "normal")
	 * @param {string} margin - The margin for the widget element. (default: '0.5rem')
	 * @param {"render"|"execute"} execution - Execution mode. (default: "render")
	 * @param {"always"|"execute"|"interaction-only"} appearance - Appearance mode. (default: "always")
	 * @param {string} callback - Name of a global function called on successful verification
	 * @param {string} errorCallback - Name of a global function called on error
	 * @param {string} expiredCallback - Name of a global function called when token expires
	 * @param {string} timeoutCallback - Name of a global function called on timeout
	 * @param {string} beforeInteractiveCallback - Name of a global function called before interactive challenge
	 * @param {string} afterInteractiveCallback - Name of a global function called after interactive challenge
	 * @param {string} unsupportedCallback - Name of a global function called when browser is unsupported
	 * @param {"multipart/form-data"|"application/x-www-form-urlencoded"|"submit"} enctype - The form enctype. (default: 'application/x-www-form-urlencoded')
	 */
	const TurnstileForm: typeof import("${name}/components/TurnstileForm").default;
	export default TurnstileForm;
}`,
};

export default { config, components };
